name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    if: github.repository == 'zheeeng/pointer-lock-movement'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: ./.github/actions/build

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./packages/pointer-lock-movement/package.json
